# yaml-language-server: $schema=https://raw.githubusercontent.com/siemens/kas/66261547b75885786777a0b9c8a4400ab81d432e/kas/schema-kas.json
header:
  version: 14

bblayers_conf_header:
  meta-common: |
    POKY_BBLAYERS_CONF_VERSION = "2"

local_conf_header:
  meta-common: |
    PACKAGE_CLASSES ?= "package_rpm"
    VOLATILE_LOG_DIR = "no"
    EXTRA_IMAGE_FEATURES ?= "debug-tweaks ssh-server-dropbear"
    # Disable splash as it causes boot and shutdown issues (for reasons unknown), but dmesg shows a lot of panics on startup
    IMAGE_FEATURES:remove = " splash"
    INIT_MANAGER="systemd"
