bblayers_conf_header:
  meta-custom: |
    POKY_BBLAYERS_CONF_VERSION = "2"
    BBPATH = "${TOPDIR}"
    BBFILES ?= ""

local_conf_header:
  meta-custom: |
    DISTRO_FEATURES:append = " bluez5 bluetooth wifi "
    IMAGE_INSTALL:append = " linux-firmware-rpidistro-bcm43430 bluez5 i2c-tools"
    VOLATILE_LOG_DIR = "no"

    INIT_MANAGER="systemd"
    IMAGE_INSTALL:append = " \
      tedge \
      tedge-state-scripts \
    "
